jabdlpc0042.1.ads 
rrmp6.keepAlive 
admin.MemoryStats 
ThreadBindingStats 
dacs 
sink 
debugLogger 
fidDatabase 
latencyMonitor 
trlsManager 
rrmpMarketDataAgent
DNSapi
rrcpTransport.1.sinkSide.rrcp.transmissionBus
sinkSide.rrcp6.transmissionBus
netRecDB 
outgoingMessages
serviceDB
sinkParser
incoming6Messages
incoming6MessagesFiltered
outgoing6Messages
aggregateServiceDataStreams
itemDatabase
userDatabase
dataStreams
inserts
userRequests
userResponses
mount1
attributes
incomingMessages
user1
mount2
user2
mount3
user3
mount4
user4
sink.server.ipc.transmissionBus
sslConnectionManager
clientSessionThread.1
clientSessionThread.2
clientSessionThread.3
clientSessionThread.4
sink.server.ripc.transmissionBus
sink.server.ws.transmissionBus.

char classList[][256] = 
{ 
    "ManagedProcess",
    "ConsumerDataStream",
    "StreamServiceMonitor",
    "ManagedProcess.SinkDist",
    "Consumer",
    "AggregateSvcDataStream",
    "WSOCKServer",
    "Consumer.UserThreadFano",
    "AggregateSvcDataStream.",
    "RIPCServer",
    "Consumer.UserThreadFano",
    "DataStreamSink6",
    "clientSessionThread",
    "SinkDistMsgs",
    "DataStreamSrc6",
    "SSLConnectionManager",
    "SinkAppMsgs",
    "RRMPParsingError",
    "IPCServer",
    "ConsumerInsert",
    "SinkNetRecSinkSvr",
    "ConsumerDb",
    "ConsumerAttributes",
    "KeepAlive",
    "ConsumerDb.SinkDist",
    "ConsumerAttributes.Sink",
    "NetRecSink",
    "GlobalThreadUser",
    "itemDatabase",
    "TransmissionBus",
    "rrcpTransmissionBus",
    "ShmemMOServerStats",
    "MarketDataAgent",
    "DNSapi",
    "TrlsManager",
    "LatencyMonitor",
    "SSLFidDatabase",
    "DebugLog",
    "DacsConnectionMgr",
    "DacsConnectionMgrClient",
    "ThreadBindingStats"
};